name: Trello API tests

on: workflow_dispatch
  
jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-versions: '20'

    - name: Install Newman
      run: npm install -g newman
    
    - name: Run test
      run: |
        newman run Trello_Vasilii/Trello_Vasilii.postman_collection.json \
        -e Trello_Vasilii/Trello_Prod.postman_environment.json \
        --env-var "APIKey=${{ secrets.APIKEY }}" \
        --env-var "APIToken=${{ secrets.APITOKEN }}" 
