name: Trello API tests

on: workflow_dispatch
  
jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Newman and HTML reporter
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra  
    
    - name: Run tests
      run: |
        newman run Trello_Vasilii/Trello_Vasilii.postman_collection.json \
        -e Trello_Vasilii/Trello_Prod.postman_environment.json \
        --env-var "APIKey=${{ secrets.APIKEY }}" \
        --env-var "APIToken=${{ secrets.APITOKEN }}" \
        --reporters htmlextra \
        --reporter-htmlextra-export newman-report.html

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: trello-html-report
        path: newman-report.html    
