name: Trello API tests

on: 
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '45 11 * * 1-5'
  workflow_dispatch:
  
jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Newman and HTML reporter
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra  
    
    - name: Run tests
      run: |
        newman run Trello_Vasilii/Trello_Vasilii.postman_collection.json \
        -e Trello_Vasilii/Trello_Prod.postman_environment.json \
        --env-var "APIKey=${{ secrets.APIKEY }}" \
        --env-var "APIToken=${{ secrets.APITOKEN }}" \
        --reporters htmlextra \
        --reporter-htmlextra-export newman-report.html

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: trello-html-report
        path: newman-report.html
        
    - name: Send html report
      uses: dawidd6/action-send-mail@v5
      env:
        CURRENT_DATE: $(date +'%d-%m-%Y_%H:%M:%S')
      with: 
        server_address: smtp.gmail.com
        username: ${{secrets.MAIL_LOGIN}}
        password: ${{secrets.MAIL_PASS}}
        server_port: 465
        subject: Github Actions job result
        to: ${{secrets.MAIL_LOGIN}}
        from: GitHub Actions - ${{ env.CURRENT_DATE }}
        body: Please find report attached
        attachments: newman-report.html
